[package]
name = "voido"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.29"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "5"
tui-textarea = "0.7"
pulldown-cmark = { version = "0.12", default-features = false }
reqwest = { version = "0.12", features = ["blocking", "json"] }
rusqlite = { version = "0.31", features = ["bundled"] }
base64 = "0.22"
unicode-width = "=0.2.0"
